# Generated by Django 2.0 on 2018-07-02 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_source', models.CharField(max_length=100, verbose_name='Source')),
                ('event_title', models.CharField(max_length=100, verbose_name='Title')),
                ('event_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('event_image', models.ImageField(blank=True, default='images/events.jpg', null=True, upload_to='images', verbose_name='Image')),
                ('event_cropped_image', models.ImageField(blank=True, default='images/events.jpg', null=True, upload_to='cropped', verbose_name='Image')),
                ('event_location', models.CharField(max_length=100, verbose_name='Location')),
                ('event_start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('event_end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('event_start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('event_end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('pub_date', models.DateTimeField(verbose_name='Publishing Date')),
                ('event_category', models.ManyToManyField(to='events.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=20, verbose_name='Location')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='publishing_location',
            field=models.ManyToManyField(to='events.Location'),
        ),
        migrations.AddField(
            model_name='attended',
            name='event',
            field=models.ForeignKey(on_delete='SET_NULL', to='events.Event'),
        ),
        migrations.AddField(
            model_name='attended',
            name='user',
            field=models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
        ),
    ]
