# Generated by Django 2.0 on 2018-07-02 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=30, verbose_name='Choice')),
                ('choice_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_source', models.CharField(max_length=100, verbose_name='Source')),
                ('poll_title', models.CharField(max_length=100, verbose_name='Title')),
                ('poll_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('poll_image', models.ImageField(blank=True, default='images/poll.jpg', null=True, upload_to='images', verbose_name='Image')),
                ('poll_deadline', models.DateTimeField(verbose_name='Deadline')),
                ('pub_date', models.DateTimeField(verbose_name='Publishing Date')),
                ('publishing_location', models.ManyToManyField(to='events.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete='SET_NULL', to='polls.Choice')),
                ('poll', models.ForeignKey(on_delete='SET_NULL', to='polls.Poll')),
                ('user', models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_poll',
            field=models.ForeignKey(on_delete='CASCADE', to='polls.Poll'),
        ),
    ]
