# Generated by Django 2.0 on 2018-07-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_source', models.CharField(max_length=100, verbose_name='Source')),
                ('notice_title', models.CharField(max_length=100, verbose_name='Title')),
                ('notice_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('notice_image', models.ImageField(blank=True, default='images/notice.jpg', null=True, upload_to='images', verbose_name='Image')),
                ('publishing_date', models.DateTimeField(verbose_name='Publishing Date')),
                ('publishing_location', models.ManyToManyField(to='events.Location')),
            ],
        ),
    ]
