# Generated by Django 2.0 on 2018-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('image', models.ImageField(default='images/request.jpg', upload_to='images', verbose_name='Image')),
                ('source', models.CharField(max_length=50, verbose_name='Source')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
    ]
