# Generated by Django 2.0 on 2018-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(default='images/request.png', upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(default='Cleanliness', max_length=30, verbose_name='Title'),
        ),
    ]
