# Generated by Django 2.0 on 2018-07-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requested',
            old_name='request',
            new_name='event',
        ),
    ]
