# Generated by Django 2.0.6 on 2018-07-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20180703_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lat',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='request',
            name='lng',
            field=models.FloatField(default=77.6),
        ),
    ]
