# Generated by Django 2.0.6 on 2018-07-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='time',
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
