# Generated by Django 2.0.6 on 2018-07-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20180711_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
