# Generated by Django 2.0.6 on 2018-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20180711_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Source'),
        ),
    ]
